title: Post
icon: page

tabs:

  content:
    icon: text
    label:
      en: Content
      de: Inhalt
    columns:

      - width: 2/3
        fields:

          beautiful:
            type: writer
            label: Beautiful title (with line breaks)
            marks: false
            inline: true
            width: 1/2

          issue:
            width: 1/2
            type: text
            label:
              en: Issue
              de: Ausgabe
            placeholder: "Essay #7"

          subtitle:
            label:
              en: Subtitle
              de: Untertitel
            type: text

          abstract:
            type: writer
            label: Abstract
            buttons: false
            maxlength: 600

          text: fields/content

          attributes:
            extends: fields/attributes
            label: Colophon

          footnotes:
            type: writer
            label: Interne Notizen (wird nicht auf der Website angezeigt)

      - width: 1/3
        sections:

          fields-1:
            type: fields
            fields:

              titleImage:
                extends: fields/image
                layout: cards
                label:
                  en: Title image
                  de: Titelbild

          uploads: sections/files

  info:
    icon: question
    label: Info
    columns:

      - width: 2/3
        fields:

          authors:
            extends: fields/people
            label:
              en: Author(s)
              de: Autoren

          downloads: fields/downloads

          links: fields/links

          keywords: fields/keywords

      - width: 1/3
        sections:

          fields-2:
            type: fields
            fields:

              date: fields/date

              color:
                type: select
                label: Semester
                options: query
                query:
                  fetch: site.semesters.toStructure
                  text: "{{ structureItem.semester }}"
                  value: "{{ structureItem.color }}"

          uploads: sections/files
