title: Post
icon: page

tabs:

  content:
    icon: text
    label:
      en: Content
      de: Inhalt
    columns:

      - width: 2/3
        fields:

          subtitle:
            label:
              en: Subtitle
              de: Untertitel
            type: text

          abstract:
            type: writer
            label: Fußnoten
            buttons: false

          text: fields/content

          footnotes:
            type: writer
            label: Fußnoten
            buttons: false

          attributes:
            extends: fields/attributes
            label: Colophon

      - width: 1/3
        sections:

          fields-1:
            type: fields
            fields:

              titleImage:
                extends: fields/image
                layout: cards
                label:
                  en: Title image
                  de: Titelbild

          uploads: sections/files

  info:
    icon: question
    label: Info
    columns:

      - width: 2/3
        fields:

          date: fields/date

          authors:
            extends: fields/people
            label:
              en: Author(s)
              de: Autoren

          downloads: fields/downloads

          links: fields/links

          keywords: fields/keywords

      - width: 1/3
        sections:

          fields-2:
            type: fields
            fields:

              categories: fields/categories

          uploads: sections/files
