title: Post

icon: page

columns:

  - width: 2/3
    fields:

      subtitle:
        type: text

      date:
        type: date
        label: Publishing date

      text: fields/content

      downloads:
        label: Downloads
        type: files

      links: fields/links

      authors:
        label: Author(s)
        type: textarea
        buttons: false

      credits: fields/credits

      keywords:
        label: Keywords
        type: tags
        accept: options
        options: query
        query:
          fetch: page.siblings.pluck("keywords", ",", true)

  - width: 1/3
    sections:

      fields2:
        type: fields
        fields:

          titleImage:
            extends: fields/image
            label: Title image

      uploads: sections/files
