title: Post

icon: page

columns:

  - width: 2/3
    fields:

      subtitle:
        label:
          en: Subtitle
          de: Untertitel
        type: text

      date:
        type: date
        label:
          en: Date
          de: Datum
        help:
          en: Can be publication date or event date
          de: Kann Veröffentlichungs- oder Veranstaltungsdatum sein

      text: fields/content

      downloads:
        label: Downloads
        type: files

      links: fields/links

      authors:
        extends: fields/people
        label:
          en: About the author(s)
          de: Über die Autoren

      credits: fields/credits

      keywords: fields/keywords

  - width: 1/3
    sections:

      fields2:
        type: fields
        fields:

          categories: fields/categories

          titleImage:
            extends: fields/image
            label:
              en: Title image
              de: Titelbild

      uploads: sections/files
