title: Wartenau

tabs:

  dashboard:
    label:
      en: Dashboard
      de: Übersicht
    icon: dashboard
    columns:

      - width: 2/3
        sections:

          posts:
            extends: sections/posts
            parent: site.page('posts')

      - width: 1/3
        sections:

          pages:
            extends: sections/pages

  settings:
    label:
      en: Settings
      de: Einstellungen
    icon: cog
    fields:

      categories:
        label:
          en: Categories
          de: Kategorien
        help:
          en: Posts can be assigned to multiple categories from the entries above
          de: Beiträge können einer oder mehreren der angelegten Kategorien zugeordnet werden
        type: structure
        fields:
          name:
            type: text
