title: Wartenau

columns:

  - width: 2/3
    sections:

      posts:
        extends: sections/posts
        parent: site.page('posts')

  - width: 1/3
    sections:

      pages:
        extends: sections/pages
